name: doorpass
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.6.0
  google_fonts: ^6.2.1
  shared_preferences: ^2.5.3
  intl : ^0.17.0
  qr_flutter: ^4.0.0
  file_picker: ^10.3.6
  qr_code_tools: ^0.2.0
  jsqr: ^0.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
